cal: main.m YearAndMonthNow.h YearAndMonthNow.m JudgeNumberRegex.h JudgeNumberRegex.m PrintYearAndMonth.h PrintYearAndMonth.m Days.h Days.m
	clang -fno-objc-arc -framework foundation main.m YearAndMonthNow.m JudgeNumberRegex.m PrintYearAndMonth.m Days.m -o cal
