cal:YearAndMonthNow.m JudgeNumberRegex.m PrintYearAndMonth.m Days.m main.m
	clang -fno-objc-arc -framework foundation
	YearAndMonthNow.m JudgeNumberRegex.m PrintYearAndMonth.m Days.m main.m -o cal
run:
	./cal
clean:
	rm cal
