MyCalendar:main.m YearAndMonthNow.m JudgeNumber.m ComputeDays.m PrintCalendar.m
	clang -fno-objc-arc -framework foundation main.m YearAndMonthNow.m JudgeNumber.m ComputeDays.m PrintCalendar.m -o MyCalendar
run:
	./MyCalendar
clean:
	rm MyCalendar

