MyFirstProject:main.m YearMonthNow.m Judge.m Days.m PrintYearMonth.m
	clang -fno-objc-arc -framework foundation main.m YearMonthNow.m Judge.m Days.m PrintYearMonth.m -o MyFirstProject
run:
	./MyFirstProject
clean:
	rm MyFirstProject

