cal : PrintYearAndMonth.m Days.m JudgeNumberRegex.m YearAndMonthNow.m main.m
	clang -fno-objc-arc -framework foundation PrintYearAndMonth.m Days.m JudgeNumberRegex.m YearAndMonthNow.m main.m -o cal

run :
	./cal

clean :
	rm PrintYearAndMonth
	rm Days
	rm JudgeNumberRegex
	rm YearAndMonthNow